generator:
  class: sfDoctrineGenerator
  param:
    model_class:           configuracion
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          configuracion
    with_doctrine_route:   true
    #actions_base_class:    sfActions

    config:
      actions: 
        _new: { credentials: God }
        _delete: { credentials: God }
      fields: ~
      list:    
        title: "Configuracion del Sitio"
        display: [Cantidad_items_por_pagina,Cantidad_podcast_por_pagina,Plantilla_defecto,Nombre_sitio,Sitio_habilitado]
        batch_actions: { }
      filter:
        class: false
      form:    ~
      edit:
        title: Editar configuracion del sitio.
      new:     ~
