Configuracion:
  tableName: configuracion
  columns:
    idConfig:
      type: integer
      primary: true
      autoincrement: true
    cantidadItemsPorPagina:
      type: integer
      notnull: true
    cantidadPodcastPorPagina:
      type: integer
      notnull: true
    plantillaDefecto:
      type: string
      notnull: true
    nombreSitio:
      type: string
      notnull: true
    sitioHabilitado:
      type: boolean
      notnull: true

Podcast:
  actAs: { Timestampable: ~ }
  tableName: podcast
  columns:
    idPodcast:
      type: integer
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      notnull: true
    descripcion:
      type: string (200)
      notnull: true
    publicado:
      type: boolean
      notnull: true
      default: 1
    imagen: 
      type: string (100)
      notnull: false
      default: no-image.png
    categoria_idCategoria:
      type: integer
      notnull: true
    user_id:
      type: integer
      notnull: true
  relations:
    categoria:
      class: Categoria
      local: categoria_idCategoria
      foreign: idCategoria
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      
Categoria:
  tableName: categoria
  columns:
    idCategoria:
      type: integer
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      notnull: true
  
Episodio:
  actAs: { Timestampable: ~ }
  tableName: episodio
  columns:
    idEpisodio:
      type: integer
      primary: true
      autoincrement: true
    nombre:
      type: string(50)
      notnull: true
    fuentemp3:
      type: string (200)
      notnull: false
    fuenteogg:
      type: string (50)
      notnull: false
    podcast_idPodcast:
      type: integer
      notnull: true
  relations:
      Podcast:
        class: Podcast
        local: podcast_idPodcast
        foreign: idPodcast
        
AdministradorPodcast:
  tableName: administradorpodcast
  columns:
    idPodcast:
      type: integer
      primary: true
      autoincrement: true
    podcast_idpodcast:
      type: integer
    user_id:
      type: integer
  relations:
      Podcast:
        class: Podcast
        local: podcast_idpodcast
        foreign: idPodcast
      User:
        class: sfGuardUser
        local: user_id
        foreign: id
